<div class="wk-customsection"data-bind="scope: 'section'">
    <p data-bind="text: customsection().msg"></p>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "section": {
                        "component": "Hirenkava_Section/js/section"
                    }
                }
            }
        }
    }
</script>